var db = require('./index');
var bcrypt = require('bcryptjs'); // Need to install bcryptjs in database package or just use mock hash for seed

async function seed() {
  try {
    // Clear existing data
    await db.query('DELETE FROM investments');
    await db.query('DELETE FROM projects');
    await db.query('DELETE FROM users');

    // Seed Users
    // Password is 'password123'
    var hashedPassword = '$2a$10$w.2Z0pQLu.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7'; 
    // Note: In a real scenario, use bcrypt.hashSync('password123', 10)
    // But since we don't want to add bcryptjs dependency just for seeding if not needed, 
    // we can skip or add it. Let's assume we add it to package.json or just insert a dummy hash.
    // For now, let's just insert a placeholder. The auth route uses bcrypt to compare.
    
    // Actually, let's just use a known hash for 'password123' generated by bcrypt
    // $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
    
    var userRes = await db.query(`
      INSERT INTO users (name, email, password)
      VALUES ($1, $2, $3)
      RETURNING id
    `, ['Demo User', 'demo@demony.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy']);
    
    var userId = userRes.rows[0].id;

    // Seed Projects
    var projects = [
      ['GreenTech Solar', 'Renewable energy for local communities', 'Renewable Energy', 100000, 75000, '🌞'],
      ['Farm Fresh Co-op', 'Organic farming cooperative', 'Agriculture', 50000, 22500, '🌾'],
      ['TechHub Workspace', 'Co-working space for tech startups', 'Real Estate', 200000, 180000, '🏢'],
      ['Artisan Bakery', 'Handcrafted breads and pastries', 'Food & Beverage', 75000, 35000, '🥖'],
      ['EcoPackage Solutions', 'Sustainable packaging materials', 'Technology', 150000, 95000, '📦']
    ];

    for (var p of projects) {
      await db.query(`
        INSERT INTO projects (name, description, category, goal_amount, raised_amount, image_url)
        VALUES ($1, $2, $3, $4, $5, $6)
      `, p);
    }

    console.log('Database seeded successfully');
    process.exit(0);
  } catch (err) {
    console.error('Error seeding database:', err);
    process.exit(1);
  }
}

seed();
